version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - VITE_PROD_PB_URL=https://learning-test.auspireroleplay.com/_
        - VITE_DEV_PB_URL=http://127.0.0.1:8090
    environment:
      - VITE_PROD_PB_URL=https://learning-test.auspireroleplay.com/_
      - VITE_DEV_PB_URL=http://127.0.0.1:8090
    volumes:
      - pb_data:/app/pb/pb_data

volumes:
  pb_data:
