version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_PROD_PB_URL=${VITE_PROD_PB_URL}
    environment:
      - VITE_PROD_PB_URL=${VITE_PROD_PB_URL}
    ports:
      - "8090:8090"
    volumes:
      - .:/app
